name: 'Verify Package Version (cargo)'
author: '@tcurdt'
description: 'Check and extract current version from package descriptor and compare it to the current tag'

inputs:
  file:
    description: 'path to Cargo.toml'
    required: true
    default: './Cargo.toml'

outputs:
  version:
    description: 'version extracted from file'

runs:
  using: 'node12'
  main: 'dist/index.js'

# branding:
#   icon: 'check-square'
#   color: 'orange'