name: ci

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4

      - name: Install
        run: npm install

      - name: Dist
        run: npm run dist

      - name: Env
        run: env

      - name: Integration Test
        uses: ./
        with:
          file: test/Cargo.toml
        id: debug

      - name: Env
        run: env

      - name: Output
        run: echo "version=${{ steps.debug.outputs.version }}"
